on:
  push:
    branches:
  workflow_dispatch:

jobs:
  secret-generator:
    runs-on: windows-latest
    outputs:
      handle: ${{ steps.generate-secret.outputs.handle }}
    steps:
      # Bước 1: Checkout code repo về Runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Thay 'some/secret-store' bang Action noi bo local
      - name: Initialize Secret Store
        uses: ./.github/actions/mock-secret-store

      # Bước 3: Tao va luu secret
      - name: generate secret
        id: generate-secret
        shell: pwsh
        run: |
          $GENERATED_SECRET = Get-Random
          Write-Host "::add-mask::$GENERATED_SECRET"
          $SECRET_HANDLE = secret-store store-secret "$GENERATED_SECRET"
          "handle=$SECRET_HANDLE" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

  secret-consumer:
    runs-on: windows-latest
    needs: secret-generator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize Secret Store
        uses: ./.github/actions/mock-secret-store

      - name: use secret
        shell: pwsh
        run: |
          $SECRET_HANDLE = "${{ needs.secret-generator.outputs.handle }}"
          $RETRIEVED_SECRET = secret-store retrieve-secret "$SECRET_HANDLE"
          Write-Host "::add-mask::$RETRIEVED_SECRET"
          Write-Host "We retrieved our masked secret: $RETRIEVED_SECRET"